### ISSUE TITLE
Live TV & DVR

### ISSUE THREAD

**Issue by ENjOY88** [wahlmanj/OpenPlex#11]
I have Openplex up and running. Great work Wahlmanj & Cyberghost themes are awesome however they don't include LiveTV & DVR library so i had to drop back to iBaa. Is there anyway to include that? Understand if its way to old of a proj. Only ended up needing to change as Plex retired my plugin!

**Comment by wahlmanj** [comment]
Likely won’t update our themes anytime soon tbh, everyone basically went to the atv4/4K with plex. If I do find the time I’ll update it, i’m glad the app worked out for ya. I’ll have to see if it’s possible to integrate my theme with ibaas/moodyblues original I know he was doing quite a bit of commits but maybe once it’s stablized I’ll take a peek into integration.
