### ISSUE TITLE
Bad installation command for Homebrew.

### ISSUE THREAD

**Issue by tregusti** [wahlmanj/OpenPlex#3]
The installation of homebrew triggered in line 2671 in https://github.com/wahlmanj/OpenPlex/blob/2497a6267a358e1ce18ac8e9be057820d82b3676/OpenPlex%200.2/AppDelegate.applescript#L2671 will fail due to this:

https://raw.githubusercontent.com/Homebrew/homebrew/go/install

**Comment by wahlmanj** [comment]
I don't use it currently for anything but thanks for the heads up in case I ever need it. I updated it in here awhile ago when the updated it https://github.com/wahlmanj/PlexConnect/blob/master/update/OSX/pillow
