### ISSUE TITLE
atvsettingsauto.bash never comes back...

### ISSUE THREAD

**Issue by Websteria** [wahlmanj/OpenPlex#4]
It sits there waiting for an ATVSettings.cfg that never seems to be generated... any ideas?

**Comment by wahlmanj** [comment]
Are you using the latest version of OpenPlex? I recommend installing from the new OpenPlex-installer.app and trying again.

**Comment by Websteria** [comment]
This is running under PlexConnect, and it does have the most recent code.... should I still reinstall?

**Comment by wahlmanj** [comment]
Yes, I provided a link in the above post. Make sure you backup your certs first prior to reinstalling.

**Comment by Websteria** [comment]
I uninstalled, and reinstalled and this is what shows when I try to load a theme:

2/20/15 10:16:15.743 AM sudo[39924]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/stop.bash
2/20/15 10:16:15.760 AM sudo[39930]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/trashbase.bash
2/20/15 10:16:21.015 AM sudo[39946]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/sudoersfix.bash
2/20/15 10:16:21.031 AM sudo[39951]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/install.bash
2/20/15 10:16:22.139 AM sudo[40350]:     jeff : TTY=unknown ; PWD=/Applications/PlexConnect/update/OSX ; USER=root ; COMMAND=/usr/bin/plexweb.bash
2/20/15 10:16:22.187 AM sudo[40375]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/purgesettings.bash
2/20/15 10:16:22.266 AM sudo[40385]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/createcert.bash
2/20/15 10:16:22.278 AM sudo[40389]:     jeff : TTY=unknown ; PWD=/Applications/PlexConnect ; USER=root ; COMMAND=/usr/bin/stop.bash
2/20/15 10:16:22.296 AM sudo[40395]:     jeff : TTY=unknown ; PWD=/Applications/PlexConnect ; USER=root ; COMMAND=/usr/bin/start.bash
2/20/15 10:16:22.318 AM sudo[40405]:     jeff : TTY=unknown ; PWD=/Applications/PlexConnect ; USER=root ; COMMAND=/usr/bin/restart.bash
2/20/15 10:16:24.580 AM soagent[580]: Can't allocate SOHelper <SOMessageHelper: 0x7fd531c94c40> inside com.apple.soagent
2/20/15 10:16:26.369 AM sudo[40423]:     jeff : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/atvsettingsauto.bash

And then it just sits there… waiting for the ATVSettings.cfg…

Thanks.
Jeff

**Comment by wahlmanj** [comment]
Install team viewer and send me a PM on the plex fourm.
