### ISSUE TITLE
OpenPlex seems to freeze while creating cert

### ISSUE THREAD

**Issue by ssuess** [wahlmanj/OpenPlex#5]
I get the spinning beach ball of death no matter which app I choose to make a cert for (trailers, imovie, WSJ), no matter if I open setup instructions before or after (well, impossible to open after because of said beachball, only choice is before generating certs) clicking on the icon, etc.  Trying to connect to the mac from the apple TV to load the cert (hoping it was created despite the spinning beachball) results in an error with no cert found. Any ideas?

**Comment by wahlmanj** [comment]
If you click the desired hijack again what happens? Do you have a log from the console.app? Have you installed the app using the latest installer.app?

**Comment by wahlmanj** [comment]
Closing issue due to no response. If you need further assistance contact me on the PlexConnect forums.

**Comment by djmlondon** [comment]
Hi,
I'm not sure if posting would reopen the ticket.

I'm suffering of exactly the same issue, whereby The Openplex app becomes non-responsive when hitting any of the three apps to hi-Jack.

I'm running latest Yosemite on a Late 2013 Core i5 iMac , mid spec with PCIe SSD and plenty of RAM, same issue on a mid 2010 Core i7 Macbook Pro also on latest OS.

Has this been seen by someone else?

**Comment by wahlmanj** [comment]
If you click the desired hijack again what happens? Do you have a log from the console.app? Have you installed the app using the latest installer.app? Contact me on the PlexConnect forums if no of this resolves the issue:

https://forums.plex.tv/index.php/forum/136-appletv-plexconnect/
