### ISSUE TITLE
Binary for 32bit Snowleopard

### ISSUE THREAD

**Issue by cuskinfor** [wahlmanj/OpenPlex#6]
Hi, I found both the installer binary and openplex binary are for x86_64 arc, I was wandering whether you can help generate a 32bit version for my old macbook pro(intel, model A1150 ) that can only support 10.6.8?

Thanks a lot!

**Comment by wahlmanj** [comment]
I will look into it for ya, gimme a few to see what xcode allows me compile for 32bit.

**Comment by cuskinfor** [comment]
Hi，

Thank you very much for your help！
Look forward to good news！
My email：inforsek@gmail.com

Thanks！
Lou

**Comment by britaliano** [comment]
Hello, I would also be very interested in a 32 bit binary.

**Comment by wahlmanj** [comment]
Installer is ready, just working on the app now. No reason to push it until its all ready. Just wanted to give everyone an update.
