### ISSUE TITLE
OSX 10.11 El Capitan firewall issue

### ISSUE THREAD

**Issue by ultraon** [wahlmanj/OpenPlex#7]
Hello and thanks for great feature!
I found that after installing OpenPlex ATV doesn't work, but if we disable firewall it works great!
I don't like disable firewall, any suggestions how we can resolve this issue?

**Comment by wahlmanj** [comment]
Its more then likely something with codesigning. Try this after you enter recovery mode (hold option @ boot). Enter a terminal while in recovery then type this:

csrutil disable

Reboot OS X then try:

sudo codesign -f -s - /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app

What exactly does your firewall say when you run into the issue if it is not python causing the issue?

**Comment by aidasan** [comment]
Hello guys
I have try on my Mac and I just need to add Python on the exception list.

Tomorrow I can do a how to for "el capitan"

Chris

**Comment by ultraon** [comment]
Hi, thx, could you please give me details, how can I add Python to exception list (as I understood correctly you meant firewall exception list)

**Comment by aidasan** [comment]
Hello guys sorry for making you waiting.
First I have powered down my aTV (Just to have a clean start and no strange request).
I don't use OpenPlex but PlexConnect from iBaa.
After turning on the FireWall in "Security & Privacy" I have run the PlexConnect.

![screen shot 2015-10-12 at 11 38 10](https://cloud.githubusercontent.com/assets/5562219/10420760/d902ba28-70d5-11e5-8959-e5f8f0646989.png)

![screen shot 2015-10-12 at 11 38 21](https://cloud.githubusercontent.com/assets/5562219/10420762/dee85bc8-70d5-11e5-82c6-354756f7436a.png)

I have immediately some popup which ask if I want to lock the app Python.app.

![screen shot 2015-10-12 at 11 40 35](https://cloud.githubusercontent.com/assets/5562219/10420789/3c591d42-70d6-11e5-899f-08c2a339d20a.png)

After this a new rule has been done.

![screen shot 2015-10-12 at 11 42 23](https://cloud.githubusercontent.com/assets/5562219/10420795/5595d96c-70d6-11e5-8410-fa5d466442e7.png)

After booting the aTV I have another popup.

![screen shot 2015-10-12 at 12 30 16](https://cloud.githubusercontent.com/assets/5562219/10421140/11622e38-70dd-11e5-8418-04ecb2f50484.png)

At this time the aTV was empty, so I restarted it.
The aTV menu was ok and Plex also.

Hope this can help.

**Comment by wahlmanj** [comment]
https://forums.plex.tv/discussion/184717/python-app-blocked-in-mac-firewall
