### ISSUE TITLE
OpenPlex installer does nothing. 

### ISSUE THREAD

**Issue by Patrick1610** [wahlmanj/OpenPlex#8]
Hi, 

I recently screwed up openplex on my Mac Mini, running El Capitan. I deleted it so I could reinstall it correctly. 
I deleted all files, downloaded the installer and ran it. It shows the popup that it will be checking OSX version and installing OpenPlex. I press "OK", enter my password and then it does nothing. 

The Mac has working internet, but the activity monitor shows that OpenPlex-installer is not using any data. (zero sent bytes, zero received bytes). 

I have no idea where it is going wrong. 
Anyone any ideas? 

Regards, 
Patrick van Bavel

**Comment by Patrick1610** [comment]
Anybody? Still unable to install it on my Mac again..

**Comment by wahlmanj** [comment]
You are not waiting for command line tools to install. It takes AWHILE for it to download it and to install it in the background silently. I tested it on a fresh VM and had no issues installing it whatsoever. The issue has to be with your machine or you are not eating long enough for CLT to install.
