### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by Figbash** [wahlmanj/OpenPlex#9]
Running a fresh install of El Capitan 10.11.4.  Manually installed newest CLT.  Running the installer from terminal gives:
2016-05-07 02:28:15.635 OpenPlex-installer[1902:213724] *** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.46/AppKit.subproj/NSCell.m:1684
2016-05-07 02:28:15.636 OpenPlex-installer[1902:213724] Invalid parameter not satisfying: aString != nil
2016-05-07 02:28:15.637 OpenPlex-installer[1902:213724] (
	0   CoreFoundation                      0x00007fff947264f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff941b673c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9472b1ca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff911fe7d6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff8557da08 -[NSCell _objectValue:forString:errorDescription:] + 180
	5   AppKit                              0x00007fff8557d824 -[NSCell setStringValue:] + 41
	6   AppKit                              0x00007fff85630b6a -[NSControl setStringValue:] + 135
	7   OpenPlex-installer                  0x0000000100001693 OpenPlex-installer + 5779
	8   Foundation                          0x00007fff911b6d6c __NSFireTimer + 95
	9   CoreFoundation                      0x00007fff946a3b94 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	10  CoreFoundation                      0x00007fff946a3823 __CFRunLoopDoTimer + 1075
	11  CoreFoundation                      0x00007fff946a337a __CFRunLoopDoTimers + 298
	12  CoreFoundation                      0x00007fff9469a871 __CFRunLoopRun + 1841
	13  CoreFoundation                      0x00007fff94699ed8 CFRunLoopRunSpecific + 296
	14  HIToolbox                           0x00007fff88ea2935 RunCurrentEventLoopInMode + 235
	15  HIToolbox                           0x00007fff88ea276f ReceiveNextEventCommon + 432
	16  HIToolbox                           0x00007fff88ea25af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	17  AppKit                              0x00007fff8554eefa _DPSNextEvent + 1067
	18  AppKit                              0x00007fff8554e32a -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	19  AppKit                              0x00007fff85542e84 -[NSApplication run] + 682
	20  AppKit                              0x00007fff8550c46c NSApplicationMain + 1176
	21  OpenPlex-installer                  0x000000010000148c OpenPlex-installer + 5260
	22  ???                                 0x0000000000000001 0x0 + 1
)

App never continues, simply says "Installing CLT or python and git" forever (I let it run overnight)

**Comment by WookieShan** [comment]
I have same issue. DRIVING ME INSANE!

**Comment by WookieShan** [comment]
MacBook Pro (13-inch, Mid 2009) / 2.26 GHz Intel Core 2 Duo / 8 GB 1067 MHz DDR3

HD failed, put new one in, decided to do clean, fresh system install and build up from there off of backups and installers. Got new OpenPlex installer. Just doesn't work. Have done everything - I'm not a total code jerk but I can hold my own IT-wise, and it simply wont work on this fresh install. Hangs as Figbash outlines above. 

Any help gratefully accepted! Craft IPA's all round!

**Comment by wahlmanj** [comment]
There is a bug that is known and will be fixed as soon as possible. 

This is an issue with the installer not the app itself by the way...Please post in the appropriate github:

https://github.com/wahlmanj/installer

**Comment by WookieShan** [comment]
Thanks a lot for the reply. 

You’re suggesting I can install an older version successfully? Where would I find this, if so?

Regards and thanks,,

**Comment by wahlmanj** [comment]
You don't need a older version of the installer but just follow this link and in the last few pages I posted a few scripts (3 in total) with instructions and a demo video on how to install OpenPlex for now...

 https://forums.plex.tv/discussion/108332/openplex-os-x-app#latest

**Comment by WookieShan** [comment]
You are, indeed, the man. 
--
441 517 1645
chrisfagg@icloud.com
http://about.me/chrisfagg

On 19 May, 2016, at 12:54 AM, wahlmanj <notifications@github.com> wrote:

You don't need a older version of the installer but just follow this link and in the last few pages I posted a few scripts (3 in total) with instructions and a demo video on how to install OpenPlex for now...
https://forums.plex.tv/discussion/108332/openplex-os-x-app#latest
